### ISSUE TITLE
where is data

### ISSUE THREAD

**Issue by qiuyinglin** [mehtanihar/pspnet#2]
when i run the below command line:
 python main.py --model pspnet train --datadir data --num-epochs 30 --num-workers 12 --batch-size 1

i have the error: 

  File "/home/ubuntu/workspace/pspnet/dataset.py", line 29, in __init__
    for f in os.listdir(self.labels_root) if is_image(f)]
FileNotFoundError: [Errno 2] No such file or directory: 'data/classes'

how to fix it? in the command line, where is --datadir data? do we need to download voc12 dataset by ourself?

thanks!

**Comment by mehtanihar** [comment]
Yes you need to download the dataset by yourself. 
You can find it here:
http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar

Create a data directory and create 'images' and 'classes' directory in it.
You need to put the "JPEGimages" in the images directory and put the segmented images (SegmentationClass) in the classes directory.
